### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by arduino5144** [wargamer/SignShop#100] opened 2020-10-18 12:39 UTC
https://mcpaste.io/7e76960f8ca11e5b

**Comment by weaves7** [comment] 2020-10-18 18:42
That crash is not caused by SignShop it seems to do with whatever is executing the Command Block chain. The only error I see from SignShop `` ERROR Nag author: 'Wargamer2010' of 'SignShop' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`` only occurs after the server has already crashed and is shutting down, that same error is fixed in future releases anyway.

**Closed by weaves7** 2020-10-18 18:42 UTC
