### ISSUE TITLE
v2.11.2 SEVERE ERROR

### ISSUE THREAD

**Issue by NorthWestTrees** [wargamer/SignShop#48] opened 2018-04-12 06:55 UTC
I just want to let you know that there is a Server Error with 2.11.2.
[SEVERE] Could not pass event SSLinkEvent to SignShop v2.11.2

Not sure what it means everything works fine players are able to buy and sell from shops but if they interact with a sign it puts out a long error message I would post the whole thing here but its a lot.

I have been good at keeping records of versions of plugins and spigot when I update the server or add new plugins so I have that if you need it.

Also, the spigot version is 1.12.1 build 60.

If you need any further information let me know I will check back here in a couple days and see if there is a reply, if not then you can contact me via the email below as I rarely get on this website so I don't know if I get an update on this issue or not.
cheecoinc0001@gmail.com

**Comment by Devinish** [comment] 2018-04-13 01:08
Without the stacktrace, we cannot help.

**Comment by NorthWestTrees** [comment] 2018-04-16 01:47
where can I find that?

**Comment by Devinish** [comment] 2018-04-16 01:59
Ah, that would be the 

>  it puts out a long error message I would post the whole thing here but its a lot.

that you were talking about

**Comment by NorthWestTrees** [comment] 2018-04-16 02:00
[2018-04-08-5.log](https://github.com/wargamer/SignShop/files/1913630/2018-04-08-5.log)
That's the server log not sure if that's what you are looking for when you say stacktrace.
Also, it only happens when making shops by the look of it, I tested it in survival and creative both give the same error.

I restarted the server before causing the error to happen.

**Comment by NorthWestTrees** [comment] 2018-04-16 02:01
6:56:40 PM [SEVERE] Could not pass event SSLinkEvent to SignShop v2.11.2
6:56:40 PM org.bukkit.event.EventException: null
6:56:40 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.wargamer2010.signshop.SignShop.scheduleEvent(SignShop.java:169) [SignShop.jar:?]
6:56:40 PM 	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:456) [SignShop.jar:?]
6:56:40 PM 	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:443) [SignShop.jar:?]
6:56:40 PM 	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:438) [SignShop.jar:?]
6:56:40 PM 	at org.wargamer2010.signshop.listeners.SignShopPlayerListener.onPlayerInteract(SignShopPlayerListener.java:230) [SignShop.jar:?]
6:56:40 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
6:56:40 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:56:40 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:56:40 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
6:56:40 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:869) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:40 PM 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
6:56:40 PM 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
6:56:41 PM 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:41 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:41 PM 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:41 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:41 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:41 PM 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
6:56:41 PM Caused by: java.lang.IncompatibleClassChangeError: Expected static method com.bekvon.bukkit.residence.Residence.getResidenceManager()Lcom/bekvon/bukkit/residence/protection/ResidenceManager;
6:56:41 PM 	at org.wargamer2010.signshop.hooks.ResidenceHook.canBuild(ResidenceHook.java:19) ~[?:?]
6:56:41 PM 	at org.wargamer2010.signshop.hooks.HookManager.canBuild(HookManager.java:51) ~[?:?]
6:56:41 PM 	at org.wargamer2010.signshop.listeners.sslisteners.SimpleBlockProtector.onSSLinkEvent(SimpleBlockProtector.java:17) ~[?:?]
6:56:41 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
6:56:41 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:56:41 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:56:41 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
6:56:41 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:56:41 PM 	... 31 more
6:57:17 PM [INFO] NorthWestTrees issued server command: /gm 0
6:57:18 PM [SEVERE] Could not pass event SSLinkEvent to SignShop v2.11.2
6:57:18 PM org.bukkit.event.EventException: null
6:57:18 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.wargamer2010.signshop.SignShop.scheduleEvent(SignShop.java:169) [SignShop.jar:?]
6:57:18 PM 	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:456) [SignShop.jar:?]
6:57:18 PM 	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:443) [SignShop.jar:?]
6:57:18 PM 	at org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:438) [SignShop.jar:?]
6:57:18 PM 	at org.wargamer2010.signshop.listeners.SignShopPlayerListener.onPlayerInteract(SignShopPlayerListener.java:230) [SignShop.jar:?]
6:57:18 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
6:57:18 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:57:18 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:57:18 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
6:57:18 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:18 PM 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:869) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
6:57:19 PM 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
6:57:19 PM Caused by: java.lang.IncompatibleClassChangeError: Expected static method com.bekvon.bukkit.residence.Residence.getResidenceManager()Lcom/bekvon/bukkit/residence/protection/ResidenceManager;
6:57:19 PM 	at org.wargamer2010.signshop.hooks.ResidenceHook.canBuild(ResidenceHook.java:19) ~[?:?]
6:57:19 PM 	at org.wargamer2010.signshop.hooks.HookManager.canBuild(HookManager.java:51) ~[?:?]
6:57:19 PM 	at org.wargamer2010.signshop.listeners.sslisteners.SimpleBlockProtector.onSSLinkEvent(SimpleBlockProtector.java:17) ~[?:?]
6:57:19 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
6:57:19 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:57:19 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
6:57:19 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
6:57:19 PM 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-edd0396-2a927e8]
6:57:19 PM 	... 31 more

**Comment by NorthWestTrees** [comment] 2018-04-16 02:02
probably easier to read if you open up the log with notepad++

**Comment by Devinish** [comment] 2018-04-16 02:08
Ah, yep.  This looks like it's a duplicate of one of our other tickets: https://github.com/wargamer/SignShop/issues/47  It's related to a change in the Residence API.  Thanks for the second report.

**Closed by Devinish** 2018-04-16 02:08 UTC
