### ISSUE TITLE
how to change [kit] plugin

### ISSUE THREAD

**Issue by KILLERBOSS1475** [wargamer/SignShop#147] opened 2022-07-19 07:07 UTC
how to change kit plugin like when u use the kit signshop it will redeem /essentials:kit instead of /kit so it means if i wanna override the /kit command with other plugin, not essentials it wont work. i wanna try change the command when executing kit signshop

**Comment by weaves7** [comment] 2022-07-19 11:42
Signshop does not have a kit command. Kits are redeemed by interacting with a [kit] sign.

**Comment by weaves7** [comment] 2022-07-19 16:19
It doesn't execute a command. You put items in a chest punch it with redstone  then punch the kit sign to activate it. Then when the sign is used it gives the items in the chest as a kit. This can only be done 1 time per player, unless they use a ResetKit  sign. You will need to make a custom kit sign in the config for each kit you want. The one that comes with SignShop is an example. You could have [kit] and [kit2] for example. If you just want to run a kit command you could use a [command] sign.

**Comment by weaves7** [comment] 2022-07-19 23:02
I am going to close this issue since the plugin works as intended. If you need more help it is usually easier in the Discord https://discord.gg/4wnyysf  Feel free to reopen the issue if you do not have access to Discord and you still need help.

**Closed by weaves7** 2022-07-19 23:02 UTC
