### ISSUE TITLE
[device] wont work with redstone

### ISSUE THREAD

**Issue by SurprisedBH** [wargamer/SignShop#64] opened 2020-03-25 15:53 UTC
It doesn't send signal if lever is connected to redstone but it does when its placed directly on the block, for exemple on a command block..

**Comment by weaves7** [comment] 2020-03-25 16:44
@SurprisedBH Please provide us with more information. What version of Spigot and SignShop? Could you provide some screenshots of how they are placed when it does not work and when it does. During development testing it works with redstone for me so we need to narrow down what is different.

**Comment by weaves7** [comment] 2020-04-13 17:38
@SurprisedBH I am closing this issue due to lack of information and not being able to reproduce it. Please reply with more information if you want it reopened.

**Closed by weaves7** 2020-04-13 17:38 UTC
Labels: MoreInfoNeeded
