### ISSUE TITLE
SignShop Named items shops break after server restart

### ISSUE THREAD

**Issue by andrewfer000** [wargamer/SignShop#91] opened 2020-08-12 00:32 UTC
I know i'm shooting out issues left and right but I also noticed shops that take named items break after the server restarts. The issue is the same with the named item trading where the shop thinks the player does not have the item when they do.

**Comment by weaves7** [comment] 2020-08-12 00:50
This is likely caused by the same Bukkit issues mentioned in #83 Could you join the Discord https://discord.gg/4wnyysf so we can chat easier?

**Comment by andrewfer000** [comment] 2020-08-12 01:29
Okay I joined. I am not running a production server with players atm (or anytime soon) so if you want me to test beta or unstable versions lmk. I'm kinda learning Java and Spigot API so maybe I will be able to help fix bugs in the future.

**Comment by weaves7** [comment] 2021-12-24 20:49
Closing due to being a duplicate issue. I also think some of these issues have been resolved by Spigot. If you have more info please provide it in #83

**Closed by weaves7** 2021-12-24 20:49 UTC
Labels: Bug, Duplicate
