### ISSUE TITLE
Items 1.13

### ISSUE THREAD

**Issue by RubenStryker** [wargamer/SignShop#52] opened 2018-11-23 18:11 UTC
Today I updated the essentials plugins on my server (dev to 1.13), since for its plugin it had the requirement to work with the worth.yml of this same plugin.

Unfortunately I see that the plugin still does not recognize many items of the new version, that's why I create this incidence to try to make this work again and continue with this plugin, because it is essential and vital for my server.

**Comment by Devinish** [comment] 2018-11-24 00:02
Duplicate of #49

**Closed by Devinish** 2018-11-24 00:02 UTC
